version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:
    # These next lines define the Android machine image executor.
    # See: https://circleci.com/docs/2.0/executor-types/
    executor:
      name: android/android-machine

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout 
      - restore_cache:
          key: android-orb-v1-

      # Get Gradle Permission
      - run:
          name: Chmod Permission
          command: sudo chmod +x ./gradlew

      # Download Dependencies
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
          key: 'android-orb-v1-{{ epoch }}'

      # Run Ktlint Format 
      - run:
          name: Ktlint Format
          command: ./gradlew ktlintFormat

      # Run Ktlint Check
      - run:
          name: Ktlint Check
          command: ./gradlew ktlintCheck
      
      # The next step will run the unit tests
      - android/run-tests:
          test-command: ./gradlew lint testDebug --continue

      # And finally run the release build
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
